# Generated by Django 4.1.7 on 2023-04-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
