# Generated by Django 4.1.7 on 2023-04-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokus", "0002_alter_user_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="visits",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
