# Generated by Django 4.1.7 on 2023-09-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokus", "0003_page_visits"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="visited_pages",),
        migrations.DeleteModel(name="Page",),
        migrations.DeleteModel(name="User",),
    ]
