# Generated by Django 4.1.7 on 2023-09-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokus", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="date_time_options", field=models.DateTimeField(),
        ),
    ]
