# Generated by Django 4.1.7 on 2023-09-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokus", "0008_remove_event_date_time_options_delete_datetimeoption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateTimeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(model_name="event", name="date_time_options",),
        migrations.AddField(
            model_name="event",
            name="date_time_options",
            field=models.ManyToManyField(to="pokus.datetimeoption"),
        ),
    ]
