# Generated by Django 4.1.7 on 2023-09-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokus", "0009_datetimeoption_remove_event_date_time_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datetimeoption",
            name="voter_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
